/**
 * scripts/http-login.js — автологин под всеми dev-ролями и запись токенов
 * в корневой .env (для VS Code REST Client).
 *
 * Запуск из корня проекта:
 *     node scripts/http-login.js
 *
 * Что делает:
 *   1. Определяет корень workspace (папка с .vscode/) или принимает --env-file.
 *   2. Логинится через POST /api/auth/login под 4 ролями (admin/moderator/
 *      employee/user — из seed.js).
 *   3. Записывает в .env переменные:
 *        HTTP_ADMIN_TOKEN, HTTP_MODERATOR_TOKEN,
 *        HTTP_EMPLOYEE_TOKEN, HTTP_USER_TOKEN
 *      + refresh-токены и userId.
 *   4. Остальные переменные в .env не трогает (дополняет/обновляет только свои).
 *
 * В .http-файлах используем:
 *     @adminToken = {{$dotenv HTTP_ADMIN_TOKEN}}
 *     @employeeToken = {{$dotenv HTTP_EMPLOYEE_TOKEN}}
 *     @userToken = {{$dotenv HTTP_USER_TOKEN}}
 *
 * ⚠️  .env с токенами ДОЛЖЕН быть в .gitignore.
 */
const fs = require('fs');
const path = require('path');
const http = require('http');
const https = require('https');

// ---------- Параметры CLI ----------
const args = process.argv.slice(2);
function getArg(flag) {
  const i = args.indexOf(flag);
  return i >= 0 && args[i + 1] ? args[i + 1] : null;
}

const SERVER_URL = getArg('--server') || 'http://localhost:5000';
const ENV_FILE = getArg('--env-file') || findWorkspaceEnv();

const ACCOUNTS = [
  { key: 'ADMIN',     username: 'admin',     password: 'admin123' },
  { key: 'MODERATOR', username: 'moderator', password: 'moderator123' },
  { key: 'EMPLOYEE',  username: 'employee',  password: 'employee123' },
  { key: 'USER',      username: 'user',      password: 'user123' },
];

/**
 * Ищет .env в корне workspace VS Code (папка с .vscode/) вверх по дереву
 * от текущей директории. Если не найдёт — берёт cwd.
 */
function findWorkspaceEnv() {
  let dir = process.cwd();
  for (let i = 0; i < 6; i++) {
    if (fs.existsSync(path.join(dir, '.vscode'))) {
      return path.join(dir, '.env');
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return path.join(process.cwd(), '.env');
}

/** Простой POST JSON без зависимостей. */
function postJson(url, body, timeoutMs = 10000) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const lib = u.protocol === 'https:' ? https : http;
    const data = JSON.stringify(body);
    const req = lib.request({
      method: 'POST',
      hostname: u.hostname,
      port: u.port || (u.protocol === 'https:' ? 443 : 80),
      path: u.pathname + u.search,
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(data),
      },
      timeout: timeoutMs,
    }, (res) => {
      let chunks = '';
      res.on('data', (c) => chunks += c);
      res.on('end', () => {
        let parsed = null;
        try { parsed = JSON.parse(chunks); } catch { /* ok */ }
        if (res.statusCode >= 400) {
          const err = new Error(`HTTP ${res.statusCode}: ${parsed?.error || chunks}`);
          err.statusCode = res.statusCode;
          return reject(err);
        }
        resolve(parsed);
      });
    });
    req.on('error', reject);
    req.on('timeout', () => req.destroy(new Error('timeout')));
    req.write(data);
    req.end();
  });
}

/** Обновляет .env: перезаписывает только строки с указанными ключами. */
function updateEnvFile(filePath, values) {
  let content = '';
  try { content = fs.readFileSync(filePath, 'utf8'); } catch { /* файла нет */ }

  const keys = new Set(Object.keys(values));
  const lines = content.split(/\r?\n/);
  const out = [];

  for (const line of lines) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=/);
    if (m && keys.has(m[1])) {
      // пропускаем — перезапишем ниже
      continue;
    }
    out.push(line);
  }

  // Убираем хвостовые пустые строки, добавляем блок
  while (out.length && out[out.length - 1].trim() === '') out.pop();
  out.push('');
  out.push('# --- HTTP tokens (auto-generated by scripts/http-login.js) ---');
  for (const [k, v] of Object.entries(values)) {
    out.push(`${k}=${v}`);
  }
  out.push('');

  fs.writeFileSync(filePath, out.join('\n'));
}

(async () => {
  console.log(`[http-login] Сервер: ${SERVER_URL}`);
  console.log(`[http-login] .env:   ${ENV_FILE}`);
  console.log('');

  const values = {};
  let ok = 0;

  for (const acc of ACCOUNTS) {
    try {
      const res = await postJson(`${SERVER_URL}/api/auth/login`, {
        usernameOrEmail: acc.username,
        password: acc.password,
      });
      if (!res || !res.accessToken) {
        console.warn(`  ⚠️  ${acc.username}: нет accessToken в ответе`);
        continue;
      }
      values[`HTTP_${acc.key}_TOKEN`] = res.accessToken;
      values[`HTTP_${acc.key}_REFRESH`] = res.refreshToken || '';
      values[`HTTP_${acc.key}_USER_ID`] = String(res.user?.id ?? '');
      console.log(`  ✅ ${acc.username} → ${acc.key} (userId=${res.user?.id})`);
      ok++;
    } catch (err) {
      console.warn(`  ❌ ${acc.username}: ${err.message}`);
    }
  }

  if (ok === 0) {
    console.error('');
    console.error('Ни один логин не прошёл. Проверьте:');
    console.error('  • сервер запущен (npm run dev в backend/)');
    console.error('  • seed создан (node seed.js в backend/)');
    console.error(`  • адрес верен (${SERVER_URL})`);
    process.exitCode = 1;
    return;
  }

  updateEnvFile(ENV_FILE, values);

  console.log('');
  console.log(`✅ Токены записаны в ${ENV_FILE} (успешных логинов: ${ok}/${ACCOUNTS.length})`);
  console.log('');
  console.log('Теперь в .http файлах доступны:');
  console.log('  @adminToken     = {{$dotenv HTTP_ADMIN_TOKEN}}');
  console.log('  @moderatorToken = {{$dotenv HTTP_MODERATOR_TOKEN}}');
  console.log('  @employeeToken  = {{$dotenv HTTP_EMPLOYEE_TOKEN}}');
  console.log('  @userToken      = {{$dotenv HTTP_USER_TOKEN}}');
})().catch((err) => {
  console.error('[http-login] Ошибка:', err.message);
  process.exitCode = 1;
});