/**
 * tests/scripts/http-login.js — автологин под всеми dev-ролями и запись
 * токенов в tests/http/.env для VS Code REST Client.
 *
 * Запуск из корня проекта:
 *     node tests/scripts/http-login.js
 *
 * Куда пишет: tests/http/.env — REST Client ищет .env в ТОЙ ЖЕ директории,
 * где лежит .http-файл (см. документацию rest-client).
 *
 * В .http-файлах: @adminToken = {{$dotenv HTTP_ADMIN_TOKEN}}
 */
const fs = require('fs');
const path = require('path');
const http = require('http');
const https = require('https');

const args = process.argv.slice(2);
function getArg(flag) {
  const i = args.indexOf(flag);
  return i >= 0 && args[i + 1] ? args[i + 1] : null;
}

const SERVER_URL = getArg('--server') || 'http://localhost:5000';

// Ищем корень проекта (папку с backend/package.json), поднимаясь вверх.
// Скрипт лежит в <root>/tests/scripts/, поэтому до корня 2 уровня.
function findProjectRoot() {
  let dir = __dirname;
  for (let i = 0; i < 6; i++) {
    if (fs.existsSync(path.join(dir, 'backend', 'package.json'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error('Не найден корень проекта (папка с backend/package.json)');
}

const PROJECT_ROOT = findProjectRoot();
const ENV_FILE = path.join(PROJECT_ROOT, 'tests', 'http', '.env');

const ACCOUNTS = [
  { key: 'ADMIN', username: 'admin', password: 'admin123' },
  { key: 'MODERATOR', username: 'moderator', password: 'moderator123' },
  { key: 'EMPLOYEE', username: 'employee', password: 'employee123' },
  { key: 'USER', username: 'user', password: 'user123' },
];

function postJson(url, body, timeoutMs = 10000) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const lib = u.protocol === 'https:' ? https : http;
    const data = JSON.stringify(body);
    const req = lib.request({
      method: 'POST',
      hostname: u.hostname,
      port: u.port || (u.protocol === 'https:' ? 443 : 80),
      path: u.pathname + u.search,
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(data),
      },
      timeout: timeoutMs,
    }, (res) => {
      let chunks = '';
      res.on('data', (c) => chunks += c);
      res.on('end', () => {
        let parsed = null;
        try { parsed = JSON.parse(chunks); } catch { /* not json */ }
        if (res.statusCode >= 400) {
          const err = new Error(`HTTP ${res.statusCode}: ${parsed?.error || chunks}`);
          err.statusCode = res.statusCode;
          return reject(err);
        }
        resolve(parsed);
      });
    });
    req.on('error', reject);
    req.on('timeout', () => req.destroy(new Error('timeout')));
    req.write(data);
    req.end();
  });
}

/**
 * Перезаписывает .env-файл: удаляет старые строки с нашими ключами,
 * дописывает свежий блок. Остальное содержимое сохраняет.
 */
const MARKER = '# --- HTTP tokens (auto-generated by tests/scripts/http-login.js) ---';

/**
 * Перезаписывает .env-файл: удаляет старые строки с нашими ключами И старый
 * маркер-комментарий, дописывает свежий блок. Остальное содержимое сохраняет.
 *
 * Важно: маркер тоже удаляем, иначе при каждом запуске он дублируется и
 * «уезжает» вниз по файлу.
 */
function updateEnvFile(filePath, values) {
  let content = '';
  try {
    content = fs.readFileSync(filePath, 'utf8');
  } catch {
    // Файла нет — создадим
  }

  const keys = new Set(Object.keys(values));
  const lines = content.split(/\r?\n/);
  const out = [];

  for (const line of lines) {
    const trimmed = line.trim();

    // Удаляем старый маркер
    if (trimmed === MARKER) continue;

    // Удаляем старые значения наших переменных
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=/);
    if (m && keys.has(m[1])) continue;

    out.push(line);
  }

  // Полностью убираем пустые строки с конца старого содержимого
  while (out.length && out[out.length - 1].trim() === '') {
    out.pop();
  }

  // Добавляем ровно одну пустую строку перед блоком токенов
  if (out.length > 0) {
    out.push('');
  }

  out.push(MARKER);

  for (const [k, v] of Object.entries(values)) {
    out.push(`${k}=${v} `);
  }

  // Ровно один перевод строки в конце файла
  out.push('');

  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(filePath, out.join('\n'));
}


(async () => {
  console.log(`[http-login] Сервер:     ${SERVER_URL}`);
  console.log(`[http-login] ProjectRoot: ${PROJECT_ROOT}`);
  console.log(`[http-login] .env:        ${ENV_FILE}`);
  console.log('');

  const values = {};
  let ok = 0;

  for (const acc of ACCOUNTS) {
    try {
      const res = await postJson(`${SERVER_URL}/api/auth/login`, {
        usernameOrEmail: acc.username,
        password: acc.password,
      });
      if (!res || !res.accessToken) {
        console.warn(`  ⚠️  ${acc.username}: нет accessToken`);
        continue;
      }
      values[`HTTP_${acc.key}_TOKEN`] = res.accessToken;
      values[`HTTP_${acc.key}_REFRESH`] = res.refreshToken || '';
      values[`HTTP_${acc.key}_USER_ID`] = String(res.user?.id ?? '');
      console.log(`  ✅ ${acc.username} → ${acc.key} (userId=${res.user?.id})`);
      ok++;
    } catch (err) {
      console.warn(`  ❌ ${acc.username}: ${err.message}`);
    }
  }

  if (ok === 0) {
    console.error('');
    console.error('Ни один логин не прошёл. Проверьте:');
    console.error('  • сервер запущен (npm run dev в backend/)');
    console.error('  • seed создан (cd backend && node seed.js)');
    console.error(`  • адрес верен (${SERVER_URL})`);
    process.exitCode = 1;
    return;
  }

  updateEnvFile(ENV_FILE, values);
  console.log('');
  console.log(`✅ Токены записаны в ${ENV_FILE} (${ok}/${ACCOUNTS.length})`);
  console.log('');
  console.log('ВАЖНО: перезагрузите окно VS Code, чтобы REST Client перечитал .env:');
  console.log('       Ctrl+Shift+P → Developer: Reload Window');
})().catch((err) => {
  console.error('[http-login] Ошибка:', err.message);
  process.exitCode = 1;
});